use hyper::{Body, Request, Response, StatusCode};
use super::common::parse_query;

// Static lookup table generated by build.rs from public/src/waf-payloads.json
#[path = "../../generated/waf_payloads.rs"]
mod waf_payloads;
use waf_payloads::WAF_ENTRIES;

pub async fn handle_waf(req: Request<Body>) -> Response<Body> {
    // Parse query string: name=<payload name> and optional method=header
    let query = req.uri().query().unwrap_or("");
    let params = parse_query(query);

    let name = match params.get("name") {
        Some(n) => n.clone(),
        None => {
            return Response::builder()
                .status(StatusCode::BAD_REQUEST)
                .body(Body::from("Missing query parameter: name"))
                .unwrap();
        }
    };
    let use_header = params.get("method").map(|m| m == "header").unwrap_or(false);

    // Look up the payload by name in the static table.
    let payload = match WAF_ENTRIES.iter().find(|e| e.name == name) {
        Some(e) => e.payload,
        None => {
            return Response::builder()
                .status(StatusCode::NOT_FOUND)
                .body(Body::from(format!("No payload found for name: {name}")))
                .unwrap();
        }
    };

    if use_header {
        // Return payload in a response header; body confirms what was sent.
        match hyper::header::HeaderValue::from_str(payload) {
            Ok(hv) => Response::builder()
                .status(StatusCode::OK)
                .header("Content-Type", "text/plain")
                .header("X-Waf-Payload", hv)
                .header("Access-Control-Allow-Origin", "*")
                .header("Access-Control-Expose-Headers", "X-Waf-Payload")
                .body(Body::from(payload))
                .unwrap(),
            Err(_) => Response::builder()
                .status(StatusCode::INTERNAL_SERVER_ERROR)
                .body(Body::from("Payload is not a valid HTTP header value"))
                .unwrap(),
        }
    } else {
        // Return payload as plain-text body.
        Response::builder()
            .status(StatusCode::OK)
            .header("Content-Type", "text/plain")
            .header("Access-Control-Allow-Origin", "*")
            .body(Body::from(payload))
            .unwrap()
    }
}
